title: Arc42 Just-The-Docs
email: chris@casualcompany.de
description: >- 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" 
url: "https://arc42.prodismy.dev" 
twitter_username: ProdIsMyDev
github_username: ProdIsMyDev

theme: just-the-docs

permalink: pretty

search_enabled: true
search:
  heading_level: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

heading_anchors: true

nav_sort: case_sensitive

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021 Christoph Koenning. Distributed by an <a href=\"https://github.com/ProdIsMyDev/Arc42-Just-The-Docs/blob/main/LICENSE\">MIT license.</a>"


gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/ProdIsMyDev/Arc42-Just-The-Docs"
gh_edit_branch: "main"

gh_edit_view_mode: "edit"
